# Generated by Django 3.2.16 on 2023-09-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20230908_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег'},
        ),
    ]
