# Generated by Django 3.2.16 on 2023-09-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
